language: julia
julia:
  - 1.0
  - 1
  - nightly
matrix:
  allow_failures:
  - julia: nightly
  fast_finish: true
notifications:
    email: false
branches:
  only: 
    - master
addons:
  apt:
    packages:
      - libgtk-3-dev
      - dvipng
      - texlive
cache:
  directories:
  # This should speed up builds
  - $HOME/.julia/artifacts

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success:
    - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();import ControlSystems; cd(joinpath(dirname(pathof(ControlSystems)), "..")); include(joinpath("docs", "make.jl"))'
