name: Documentation

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: 
      - '*'

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Install apt deps
        run: sudo apt-get install libgtk-3-dev dvipng texlive
      - name: Setup docs environment
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - name: Test docs
        run: |
          julia --project=docs -e '
            using Documenter: doctest
            using ControlSystems
            doctest(ControlSystems)''
      - name: Generate documentation
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
